apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  selector:
    app: php
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp1234
  labels:
    app: php
    tier: frontend
spec:
  selector:
    matchLabels:
      app: php
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: php
        tier: frontend
    spec:
      containers:
      - name: webapp1234
        image: mrchelsea/dcapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8081

